# This is a basic workflow to help you get started with Actions

name: Java Maven Notificación automatizada

on:
  # Nuestra rama principal es develop y la de producción es master
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ejecutar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Maven
        run: mvn -B package --file pom.xml
      - name: Notificar fallos al correo
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          server_port: 465
          # Required mail server username:
          username: ${{secrets.lomitofrito.lomcrafteo@gmail.com}}
          password: ${{secrets.TeQueremos}}
          # Required mail subject:
          subject: Fallo despliegue ${{ github.event_name }} en ${{github.repository}}
          # Required recipients' addresses:
          to: kennethleo1@hotmail.com, ortizrubio09@gmail.com
          # Required sender full name (address can be skipped):
          from: Wiseman # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build de puja que puja en el repositorio ${{github.repository}} fallo!
