# This is a basic workflow to help you get started with Actions

name: Java Maven Notificación automatizada

on:
  # Nuestra rama principal es develop y la de producción es master
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ejecutar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Maven
        run: mvn -B package --file pom.xml
      - name: Discord notification
        if: failure()
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/846528076346294322/mHgqCDEwT26vmUefhztEKNaYtJG18BRjm3qURkukMesdk9o03PnK8IqDWWninlPOlJt4
          DISCORD_USERNAME: WISEMAN
        uses: Ilshidur/action-discord@master
        with: 
          args: "Fallo despliegue ${{ github.event_name }} \nRepositorio: ${{ github.repository }} \nRama: ${{ github.ref }}"
      - name: Discord notification
        if: failure()
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/846528076346294322/mHgqCDEwT26vmUefhztEKNaYtJG18BRjm3qURkukMesdk9o03PnK8IqDWWninlPOlJt4
        uses: Ilshidur/action-discord@master
